#ifndef CHESSCADE_ADAPTER_REGISTER_TYPES_H
#define CHESSCADE_ADAPTER_REGISTER_TYPES_H

#include "modules/register_module_types.h"

void initialize_chesscade_adapter_module(ModuleInitializationLevel p_level);
void uninitialize_chesscade_adapter_module(ModuleInitializationLevel p_level);

#endif // CHESSCADE_ADAPTER_REGISTER_TYPES_H